### ISSUE TITLE
FAILED jsp: java.lang.NoClassDefFoundError: org/apache/jasper/runtime/JspApplicationContextImpl

### ISSUE THREAD

**Issue by thanhtruongminh** [kreyssel/selenium2-visualdiff#4]
Hi author,
Thanks for sharing it.
But I run to an issue while running mvn clean install
Please help me!

[INFO] Reactor Summary:
[INFO] 
[INFO] VisualDiff :: Project .............................. SUCCESS [  0.709 s]
[INFO] VisualDiff :: Core Library ......................... SUCCESS [  0.627 s]
[INFO] VisualDiff :: Maven Plugin ......................... SUCCESS [  1.226 s]
[INFO] VisualDiff :: Integration Tests .................... SUCCESS [ 21.845 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24.500 s
[INFO] Finished at: 2017-06-23T16:20:47+07:00
[INFO] Final Memory: 39M/393M
[INFO] ------------------------------------------------------------------------
[WARNING] FAILED jsp: java.lang.NoClassDefFoundError: org/apache/jasper/runtime/JspApplicationContextImpl
Exception in thread "StopJettyPluginMonitor" java.lang.NoClassDefFoundError: org/apache/jasper/runtime/JspApplicationContextImpl
	at org.apache.jasper.servlet.JspServlet.destroy(JspServlet.java:411)
	at org.eclipse.jetty.servlet.ServletHolder.destroyInstance(ServletHolder.java:310)
	at org.eclipse.jetty.servlet.ServletHolder.doStop(ServletHolder.java:284)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:83)
	at org.eclipse.jetty.servlet.ServletHandler.doStop(ServletHandler.java:199)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:83)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStop(HandlerWrapper.java:101)
	at org.eclipse.jetty.security.SecurityHandler.doStop(SecurityHandler.java:350)
	at org.eclipse.jetty.security.ConstraintSecurityHandler.doStop(ConstraintSecurityHandler.java:237)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:83)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStop(HandlerWrapper.java:101)
	at org.eclipse.jetty.server.session.SessionHandler.doStop(SessionHandler.java:124)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:83)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStop(HandlerWrapper.java:101)
	at org.eclipse.jetty.server.handler.ContextHandler.doStop(ContextHandler.java:671)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStop(ServletContextHandler.java:143)
	at org.eclipse.jetty.webapp.WebAppContext.doStop(WebAppContext.java:473)
	at org.mortbay.jetty.plugin.JettyWebAppContext.doStop(JettyWebAppContext.java:187)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:83)
	at org.eclipse.jetty.server.handler.HandlerCollection.doStop(HandlerCollection.java:245)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:83)
	at org.eclipse.jetty.server.handler.HandlerCollection.doStop(HandlerCollection.java:245)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:83)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStop(HandlerWrapper.java:101)
	at org.eclipse.jetty.server.Server.doStop(Server.java:319)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:83)
	at org.mortbay.jetty.plugin.Monitor.run(Monitor.java:102)
Caused by: java.lang.ClassNotFoundException: org.apache.jasper.runtime.JspApplicationContextImpl
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 27 more
[WARNING] FAILED org.eclipse.jetty.servlet.ServletHandler@b016a8e: java.lang.NoClassDefFoundError: org/apache/jasper/runtime/JspApplicationContextImpl
[WARNING] FAILED org.eclipse.jetty.security.ConstraintSecurityHandler@5c6859e: java.lang.NoClassDefFoundError: org/apache/jasper/runtime/JspApplicationContextImpl
[WARNING] FAILED org.eclipse.jetty.server.session.SessionHandler@1f901fe: java.lang.NoClassDefFoundError: org/apache/jasper/runtime/JspApplicationContextImpl
[INFO] stopped o.m.j.p.JettyWebAppContext{/,file:/D:/SeleniumDemo/project/selenium2-visualdiff-master/it/src/main/webapp/},file:/D:/SeleniumDemo/project/selenium2-visualdiff-master/it/src/main/webapp/
[WARNING] FAILED o.m.j.p.JettyWebAppContext{/,file:/D:/SeleniumDemo/project/selenium2-visualdiff-master/it/src/main/webapp/},file:/D:/SeleniumDemo/project/selenium2-visualdiff-master/it/src/main/webapp/: java.lang.NoClassDefFoundError: org/apache/jasper/runtime/JspApplicationContextImpl
[WARNING] FAILED org.eclipse.jetty.server.handler.ContextHandlerCollection@44fb8fa5: java.lang.NoClassDefFoundError: org/apache/jasper/runtime/JspApplicationContextImpl
[WARNING] FAILED org.eclipse.jetty.server.handler.HandlerCollection@442ec8ae: java.lang.NoClassDefFoundError: org/apache/jasper/runtime/JspApplicationContextImpl
[WARNING] FAILED org.mortbay.jetty.plugin.JettyServer@17d2b646: java.lang.NoClassDefFoundError: org/apache/jasper/runtime/JspApplicationContextImpl
[WARNING] FAILED jsp: java.lang.NoClassDefFoundError: org/apache/jasper/runtime/JspApplicationContextImpl
[WARNING] FAILED org.eclipse.jetty.servlet.ServletHandler@b016a8e: java.lang.NoClassDefFoundError: org/apache/jasper/runtime/JspApplicationContextImpl
[WARNING] FAILED org.eclipse.jetty.security.ConstraintSecurityHandler@5c6859e: java.lang.NoClassDefFoundError: org/apache/jasper/runtime/JspApplicationContextImpl
[WARNING] FAILED org.eclipse.jetty.server.session.SessionHandler@1f901fe: java.lang.NoClassDefFoundError: org/apache/jasper/runtime/JspApplicationContextImpl
[INFO] stopped o.m.j.p.JettyWebAppContext{/,file:/D:/SeleniumDemo/project/selenium2-visualdiff-master/it/src/main/webapp/},file:/D:/SeleniumDemo/project/selenium2-visualdiff-master/it/src/main/webapp/
[WARNING] FAILED o.m.j.p.JettyWebAppContext{/,file:/D:/SeleniumDemo/project/selenium2-visualdiff-master/it/src/main/webapp/},file:/D:/SeleniumDemo/project/selenium2-visualdiff-master/it/src/main/webapp/: java.lang.NoClassDefFoundError: org/apache/jasper/runtime/JspApplicationContextImpl
[WARNING] FAILED org.eclipse.jetty.server.handler.ContextHandlerCollection@44fb8fa5: java.lang.NoClassDefFoundError: org/apache/jasper/runtime/JspApplicationContextImpl
[WARNING] FAILED org.eclipse.jetty.server.handler.HandlerCollection@442ec8ae: java.lang.NoClassDefFoundError: org/apache/jasper/runtime/JspApplicationContextImpl
[WARNING] FAILED org.mortbay.jetty.plugin.JettyServer@17d2b646: java.lang.NoClassDefFoundError: org/apache/jasper/runtime/JspApplicationContextImpl
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: org/apache/jasper/runtime/JspApplicationContextImpl
	at org.apache.jasper.servlet.JspServlet.destroy(JspServlet.java:411)
	at org.eclipse.jetty.servlet.ServletHolder.destroyInstance(ServletHolder.java:310)
	at org.eclipse.jetty.servlet.ServletHolder.doStop(ServletHolder.java:284)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:83)
	at org.eclipse.jetty.servlet.ServletHandler.doStop(ServletHandler.java:199)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:83)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStop(HandlerWrapper.java:101)
	at org.eclipse.jetty.security.SecurityHandler.doStop(SecurityHandler.java:350)
	at org.eclipse.jetty.security.ConstraintSecurityHandler.doStop(ConstraintSecurityHandler.java:237)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:83)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStop(HandlerWrapper.java:101)
	at org.eclipse.jetty.server.session.SessionHandler.doStop(SessionHandler.java:124)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:83)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStop(HandlerWrapper.java:101)
	at org.eclipse.jetty.server.handler.ContextHandler.doStop(ContextHandler.java:671)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStop(ServletContextHandler.java:143)
	at org.eclipse.jetty.webapp.WebAppContext.doStop(WebAppContext.java:473)
	at org.mortbay.jetty.plugin.JettyWebAppContext.doStop(JettyWebAppContext.java:187)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:83)
	at org.eclipse.jetty.server.handler.HandlerCollection.doStop(HandlerCollection.java:245)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:83)
	at org.eclipse.jetty.server.handler.HandlerCollection.doStop(HandlerCollection.java:245)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:83)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStop(HandlerWrapper.java:101)
	at org.eclipse.jetty.server.Server.doStop(Server.java:319)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:83)
	at org.eclipse.jetty.util.thread.ShutdownThread.run(ShutdownThread.java:121)

**Comment by joakime** [comment]
Jetty 7 (`o.m.j.p.JettyWebAppContext`) was declared EOL in Oct 2014, see #5

**Comment by thanhtruongminh** [comment]
Dear joakime,
How can I resolve it? which version I should upgrade?
Please advice me.
Many thanks!

**Comment by thanhtruongminh** [comment]
ah,
I saw your comment,
Thank you ^^
